#!/bin/bash
# Usage: qbt-status [filter]
# Filters: downloading, completed, active, inactive (optional, default: all)
# Returns: name, state, progress%, downloaded/total in GB, speed, ETA
FILTER=""
if [ -n "$1" ]; then
    FILTER="-q filter=$1"
fi
api-call qbt GET /torrents/info $FILTER | jq '[.[] | {name: .name, hash: .hash, state: .state, progress: ((.progress * 100 | round | tostring) + "%"), downloaded_gb: ((.size / 1073741824 * 100 | round) / 100), total_gb: ((.total_size / 1073741824 * 100 | round) / 100), dlspeed_mbs: ((.dlspeed / 1048576 * 100 | round) / 100), eta: .eta}]'
